package com.android.systemui.statusbar.policy;

import com.android.systemui.R;
import com.android.systemui.statusbar.policy.MobileSignalController.MobileIconGroup;

public class HwTelephonyIcons {
    public static final IconGroup CHARGED_WIFI = new IconGroup("Wi-Fi Icons", CHARGED_WIFI_SIGNAL_STRENGTH, WifiIcons.QS_WIFI_SIGNAL_STRENGTH, AccessibilityContentDescriptions.WIFI_CONNECTION_STRENGTH, R.drawable.stat_sys_wifi_signal_null, R.drawable.ic_qs_wifi_no_network, R.drawable.stat_sys_wifi_signal_null, R.drawable.ic_qs_wifi_no_network, R.string.accessibility_no_wifi);
    static final int[][] CHARGED_WIFI_SIGNAL_STRENGTH = new int[][]{new int[]{R.drawable.stat_sys_charged_wifi_signal_0, R.drawable.stat_sys_charged_wifi_signal_1, R.drawable.stat_sys_charged_wifi_signal_2, R.drawable.stat_sys_charged_wifi_signal_3, R.drawable.stat_sys_charged_wifi_signal_4}, new int[]{R.drawable.stat_sys_charged_wifi_signal_0, R.drawable.stat_sys_charged_wifi_signal_1, R.drawable.stat_sys_charged_wifi_signal_2, R.drawable.stat_sys_charged_wifi_signal_3, R.drawable.stat_sys_charged_wifi_signal_4}};
    static final MobileIconGroup FORGPLUS = new MobileIconGroup("4GPLUS", TelephonyIcons.TELEPHONY_SIGNAL_STRENGTH, TelephonyIcons.QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_lte, R.drawable.stat_sys_data_fully_connected_4gplus, true, R.drawable.ic_qs_signal_4g);
    public static final MobileIconGroup H_PLUS = new MobileIconGroup("H+", TelephonyIcons.TELEPHONY_SIGNAL_STRENGTH, TelephonyIcons.QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_hspa_plus, R.drawable.stat_sys_data_connected_hplus, true, R.drawable.ic_qs_signal_h);
    static final MobileIconGroup IWLAN = new MobileIconGroup("IWLAN", TelephonyIcons.TELEPHONY_SIGNAL_STRENGTH, TelephonyIcons.QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], 0, 0, false, 0);
    static final int[] QS_DATA_H_PLUS = new int[]{R.drawable.ic_qs_signal_hplus, R.drawable.ic_qs_signal_hplus};
    static final int[][] QS_TELEPHONY_SIGNAL_STRENGTH_SIGBAR_5 = new int[][]{new int[]{R.drawable.stat_sys_signal_five_0, R.drawable.stat_sys_signal_five_1, R.drawable.stat_sys_signal_five_2, R.drawable.stat_sys_signal_five_3, R.drawable.stat_sys_signal_five_4, R.drawable.stat_sys_signal_five_5}, new int[]{R.drawable.stat_sys_signal_five_0_fully, R.drawable.stat_sys_signal_five_1_fully, R.drawable.stat_sys_signal_five_2_fully, R.drawable.stat_sys_signal_five_3_fully, R.drawable.stat_sys_signal_five_4_fully, R.drawable.stat_sys_signal_five_5_fully}};
    static final MobileIconGroup TDS = new MobileIconGroup("TDS", TelephonyIcons.TELEPHONY_SIGNAL_STRENGTH, TelephonyIcons.QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_tds, R.drawable.stat_sys_data_fully_connected_3g, true, R.drawable.ic_qs_signal_3g);
    static final int[][] TELEPHONY_SIGNAL_STRENGTH_5BARS = new int[][]{new int[]{R.drawable.stat_sys_signal_five_0, R.drawable.stat_sys_signal_five_1, R.drawable.stat_sys_signal_five_2, R.drawable.stat_sys_signal_five_3, R.drawable.stat_sys_signal_five_4, R.drawable.stat_sys_signal_five_5}, new int[]{R.drawable.stat_sys_signal_five_0_fully, R.drawable.stat_sys_signal_five_1_fully, R.drawable.stat_sys_signal_five_2_fully, R.drawable.stat_sys_signal_five_3_fully, R.drawable.stat_sys_signal_five_4_fully, R.drawable.stat_sys_signal_five_5_fully}};
    static final int[][] TELEPHONY_SIGNAL_TYPE_TJT = new int[][]{new int[]{R.drawable.stat_sys_tjt_signal_0, R.drawable.stat_sys_tjt_signal_1, R.drawable.stat_sys_tjt_signal_2, R.drawable.stat_sys_tjt_signal_3, R.drawable.stat_sys_tjt_signal_4}, new int[]{R.drawable.stat_sys_tjt_signal_0_fully, R.drawable.stat_sys_tjt_signal_1_fully, R.drawable.stat_sys_tjt_signal_2_fully, R.drawable.stat_sys_tjt_signal_3_fully, R.drawable.stat_sys_tjt_signal_4_fully}};
    static final int[][] TELEPHONY_TJT_SIGNAL_STRENGTH_FIVE = new int[][]{new int[]{R.drawable.ic_statusbar_signal_tjt_0, R.drawable.ic_statusbar_signal_tjt_1, R.drawable.ic_statusbar_signal_tjt_2, R.drawable.ic_statusbar_signal_tjt_3, R.drawable.ic_statusbar_signal_tjt_4, R.drawable.ic_statusbar_signal_tjt_5}, new int[]{R.drawable.ic_statusbar_signal_tjt_0_fully, R.drawable.ic_statusbar_signal_tjt_1_fully, R.drawable.ic_statusbar_signal_tjt_2_fully, R.drawable.ic_statusbar_signal_tjt_3_fully, R.drawable.ic_statusbar_signal_tjt_4_fully, R.drawable.ic_statusbar_signal_tjt_5_fully}};
    public static final MobileIconGroup TIANJITONG = new MobileIconGroup("TIANGJITONG", TELEPHONY_SIGNAL_TYPE_TJT, TelephonyIcons.QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, R.drawable.stat_sys_signal_tianjitong_null, 0, R.drawable.stat_sys_signal_tianjitong_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_3g, R.drawable.stat_sys_data_fully_connected_3g, true, R.drawable.ic_qs_signal_3g);
    public static final IconGroup TIANJITONG_WIFI = new IconGroup("Wi-Fi Icons", TJT_WIFI_SIGNAL_STRENGTH, WifiIcons.QS_WIFI_SIGNAL_STRENGTH, AccessibilityContentDescriptions.WIFI_CONNECTION_STRENGTH, R.drawable.stat_sys_wifi_signal_null, R.drawable.ic_qs_wifi_no_network, R.drawable.stat_sys_wifi_signal_null, R.drawable.ic_qs_wifi_no_network, R.string.accessibility_no_wifi);
    static final int[][] TJT_WIFI_SIGNAL_STRENGTH = new int[][]{new int[]{R.drawable.stat_sys_cloud_wifi_signal_0, R.drawable.stat_sys_cloud_wifi_signal_1, R.drawable.stat_sys_cloud_wifi_signal_2, R.drawable.stat_sys_cloud_wifi_signal_3, R.drawable.stat_sys_cloud_wifi_signal_4}, new int[]{R.drawable.stat_sys_cloud_wifi_signal_full_0, R.drawable.stat_sys_cloud_wifi_signal_full_1, R.drawable.stat_sys_cloud_wifi_signal_full_2, R.drawable.stat_sys_cloud_wifi_signal_full_3, R.drawable.stat_sys_cloud_wifi_signal_full_4}};
    public static final MobileIconGroup TWO_G = new MobileIconGroup("2G", TelephonyIcons.TELEPHONY_SIGNAL_STRENGTH, TelephonyIcons.QS_TELEPHONY_SIGNAL_STRENGTH, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH, 0, 0, R.drawable.stat_sys_signal_null, R.drawable.ic_qs_signal_no_signal, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH[0], R.string.accessibility_data_connection_gprs, R.drawable.stat_sys_data_connected_2g, true, R.drawable.ic_qs_signal_g);

    public static MobileIconGroup getFiveSignalIconGroup(MobileIconGroup icons) {
        return new MobileIconGroup(icons.mName, TELEPHONY_SIGNAL_STRENGTH_5BARS, QS_TELEPHONY_SIGNAL_STRENGTH_SIGBAR_5, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH_SIGBAR_5, icons.mSbNullState, icons.mQsNullState, R.drawable.stat_sys_signal_five_null, R.drawable.stat_sys_signal_five_null, AccessibilityContentDescriptions.PHONE_SIGNAL_STRENGTH_SIGBAR_5[0], icons.mDataContentDescription, icons.mDataType, icons.mIsWide, icons.mQsDataType);
    }

    public static int getFiveSignalIcons(int inetcon, int length) {
        if (inetcon < 0 || inetcon >= 2 || length < 0 || length >= 6) {
            return TELEPHONY_SIGNAL_STRENGTH_5BARS[0][0];
        }
        return TELEPHONY_SIGNAL_STRENGTH_5BARS[inetcon][length];
    }

    public static int getFiveTJTSignalIcons(int inetcon, int masterLevel) {
        if (inetcon < 0 || inetcon >= 2 || masterLevel < 0 || masterLevel >= 6) {
            return TELEPHONY_SIGNAL_TYPE_TJT[0][0];
        }
        return TELEPHONY_TJT_SIGNAL_STRENGTH_FIVE[inetcon][masterLevel];
    }
}
