package com.android.server.location.gnsschrlog;

public class CSegEVENT_GPS_DAILY_CNT_REPORT extends ChrLogBaseEventModel {
    public ENCEventId enEventId = new ENCEventId();
    public LogInt iAgpsConnCnt = new LogInt();
    public LogInt iAgpsConnFailedCnt = new LogInt();
    public LogInt iAutoNavi_cnt = new LogInt();
    public LogInt iAvgPosAcc = new LogInt();
    public LogInt iAvgTTFF = new LogInt();
    public LogInt iBaidu_cnt = new LogInt();
    public LogInt iCareland_cnt = new LogInt();
    public LogInt iNtpFlashSuccCnt = new LogInt();
    public LogInt iNtpMobileFailCnt = new LogInt();
    public LogInt iNtpReqCnt = new LogInt();
    public LogInt iNtpWifiFailCnt = new LogInt();
    public LogInt iRstartCnt = new LogInt();
    public LogInt iXtraDloadCnt = new LogInt();
    public LogInt iXtraReqCnt = new LogInt();
    public LogInt igpserroruploadCnt = new LogInt();
    public LogInt igpsreqCnt = new LogInt();
    public LogInt inetworkReqCnt = new LogInt();
    public LogInt inetworktimeoutCnt = new LogInt();
    public LogLong lAllPosTime = new LogLong();
    public LogString strIsCn0Good = new LogString(6);
    public LogString strIsCn0Valied = new LogString(6);
    public LogDate tmTimeStamp = new LogDate(6);
    public LogByte ucCardIndex = new LogByte();
    public LogByte ucErrorCode = new LogByte();
    public LogByte ucGpsRfBitMask = new LogByte();
    public LogShort usLen = new LogShort();
    public LogShort usSubErrorCode = new LogShort();

    public CSegEVENT_GPS_DAILY_CNT_REPORT() {
        this.lengthMap.put("enEventId", Integer.valueOf(1));
        this.fieldMap.put("enEventId", this.enEventId);
        this.lengthMap.put("usLen", Integer.valueOf(2));
        this.fieldMap.put("usLen", this.usLen);
        this.lengthMap.put("tmTimeStamp", Integer.valueOf(6));
        this.fieldMap.put("tmTimeStamp", this.tmTimeStamp);
        this.lengthMap.put("ucErrorCode", Integer.valueOf(1));
        this.fieldMap.put("ucErrorCode", this.ucErrorCode);
        this.lengthMap.put("ucCardIndex", Integer.valueOf(1));
        this.fieldMap.put("ucCardIndex", this.ucCardIndex);
        this.lengthMap.put("usSubErrorCode", Integer.valueOf(2));
        this.fieldMap.put("usSubErrorCode", this.usSubErrorCode);
        this.lengthMap.put("inetworktimeoutCnt", Integer.valueOf(4));
        this.fieldMap.put("inetworktimeoutCnt", this.inetworktimeoutCnt);
        this.lengthMap.put("inetworkReqCnt", Integer.valueOf(4));
        this.fieldMap.put("inetworkReqCnt", this.inetworkReqCnt);
        this.lengthMap.put("igpserroruploadCnt", Integer.valueOf(4));
        this.fieldMap.put("igpserroruploadCnt", this.igpserroruploadCnt);
        this.lengthMap.put("igpsreqCnt", Integer.valueOf(4));
        this.fieldMap.put("igpsreqCnt", this.igpsreqCnt);
        this.lengthMap.put("iRstartCnt", Integer.valueOf(4));
        this.fieldMap.put("iRstartCnt", this.iRstartCnt);
        this.lengthMap.put("iXtraDloadCnt", Integer.valueOf(4));
        this.fieldMap.put("iXtraDloadCnt", this.iXtraDloadCnt);
        this.lengthMap.put("iXtraReqCnt", Integer.valueOf(4));
        this.fieldMap.put("iXtraReqCnt", this.iXtraReqCnt);
        this.lengthMap.put("iNtpWifiFailCnt", Integer.valueOf(4));
        this.fieldMap.put("iNtpWifiFailCnt", this.iNtpWifiFailCnt);
        this.lengthMap.put("iNtpMobileFailCnt", Integer.valueOf(4));
        this.fieldMap.put("iNtpMobileFailCnt", this.iNtpMobileFailCnt);
        this.lengthMap.put("iNtpFlashSuccCnt", Integer.valueOf(4));
        this.fieldMap.put("iNtpFlashSuccCnt", this.iNtpFlashSuccCnt);
        this.lengthMap.put("iNtpReqCnt", Integer.valueOf(4));
        this.fieldMap.put("iNtpReqCnt", this.iNtpReqCnt);
        this.lengthMap.put("strIsCn0Valied", Integer.valueOf(6));
        this.fieldMap.put("strIsCn0Valied", this.strIsCn0Valied);
        this.lengthMap.put("strIsCn0Good", Integer.valueOf(6));
        this.fieldMap.put("strIsCn0Good", this.strIsCn0Good);
        this.lengthMap.put("iAgpsConnFailedCnt", Integer.valueOf(4));
        this.fieldMap.put("iAgpsConnFailedCnt", this.iAgpsConnFailedCnt);
        this.lengthMap.put("iAgpsConnCnt", Integer.valueOf(4));
        this.fieldMap.put("iAgpsConnCnt", this.iAgpsConnCnt);
        this.lengthMap.put("iAvgTTFF", Integer.valueOf(4));
        this.fieldMap.put("iAvgTTFF", this.iAvgTTFF);
        this.lengthMap.put("iAvgPosAcc", Integer.valueOf(4));
        this.fieldMap.put("iAvgPosAcc", this.iAvgPosAcc);
        this.lengthMap.put("lAllPosTime", Integer.valueOf(8));
        this.fieldMap.put("lAllPosTime", this.lAllPosTime);
        this.lengthMap.put("iBaidu_cnt", Integer.valueOf(4));
        this.fieldMap.put("iBaidu_cnt", this.iBaidu_cnt);
        this.lengthMap.put("iAutoNavi_cnt", Integer.valueOf(4));
        this.fieldMap.put("iAutoNavi_cnt", this.iAutoNavi_cnt);
        this.lengthMap.put("iCareland_cnt", Integer.valueOf(4));
        this.fieldMap.put("iCareland_cnt", this.iCareland_cnt);
        this.lengthMap.put("ucGpsRfBitMask", Integer.valueOf(1));
        this.fieldMap.put("ucGpsRfBitMask", this.ucGpsRfBitMask);
        this.enEventId.setValue("GPS_DAILY_CNT_REPORT");
        this.usLen.setValue(getTotalLen());
    }
}
