package com.huawei.cspcommon.util;

public class SearchContract$ContactQuery {
    public static final String[] CONTACTS_SEARCH_PROJECTION_ALTERNATIVE = new String[]{"contact_id", "display_name_alt", "contact_presence", "contact_status", "photo_id", "photo_thumb_uri", "lookup", "raw_contact_id", "sort_key_alt", "raw_contact_id", "times_contacted", "company", "starred", "is_camcard", "raw_contact_id", "number_ori", "organization_ori", "nick_name_ori", "email_ori", "address_ori", "note_ori", "im_ori"};
    public static final String[] CONTACTS_SEARCH_PROJECTION_ALTERNATIVE_PRIVATE = new String[]{"contact_id", "display_name_alt", "contact_presence", "contact_status", "photo_id", "photo_thumb_uri", "lookup", "raw_contact_id", "sort_key_alt", "raw_contact_id", "times_contacted", "company", "is_private", "starred", "is_camcard", "raw_contact_id", "number_ori", "organization_ori", "nick_name_ori", "email_ori", "address_ori", "note_ori", "im_ori"};
    public static final String[] CONTACTS_SEARCH_PROJECTION_PRIMARY = new String[]{"contact_id", "display_name", "contact_presence", "contact_status", "photo_id", "photo_thumb_uri", "lookup", "raw_contact_id", "sort_key", "raw_contact_id", "times_contacted", "company", "starred", "is_camcard", "raw_contact_id", "number_ori", "organization_ori", "nick_name_ori", "email_ori", "address_ori", "note_ori", "im_ori"};
    public static final String[] CONTACTS_SEARCH_PROJECTION_PRIMARY_PRIVATE = new String[]{"contact_id", "display_name", "contact_presence", "contact_status", "photo_id", "photo_thumb_uri", "lookup", "raw_contact_id", "sort_key", "raw_contact_id", "times_contacted", "company", "is_private", "starred", "is_camcard", "raw_contact_id", "number_ori", "organization_ori", "nick_name_ori", "email_ori", "address_ori", "note_ori", "im_ori"};
    static final String[] SMART_DIAL_SEARCH_PROJECTION = new String[]{"_id", "display_name", "sort_key", "photo_id", "photo_uri", "data1", "data2", "data3", "data10", "data11", "contact_id", "lookup", "times_contacted", "company", "data4", "is_primary"};
}
