package com.fyusion.sdk.common.ext;

import com.fyusion.sdk.common.e;

/* compiled from: Unknown */
public class k {
    public static float A = 0.05f;
    public static boolean B = false;
    public static int C = 320;
    public static boolean D = false;
    public static boolean E = true;
    public static String F = "fyuse.processing";
    public static boolean G = false;
    public static boolean H = false;
    public static int I = 200;
    public static int J = 1;
    public static int K = 40;
    public static float L = 0.5f;
    public static float M = 30.0f;
    public static boolean N = true;
    public static float O = 20.0f;
    public static boolean P = true;
    public static float Q = 0.85f;
    public static int R = 100;
    public static int S = 320;
    public static float T = 0.03f;
    public static float U = 2.0f;
    public static int V = 34;
    public static float W = 0.85f;
    public static boolean X = false;
    public static boolean Y = false;
    public static String Z = "settings.xml";
    public static String a = "1.1";
    public static String aA = "fyuse_h264_slice%d.mp4";
    public static String aB = "processing_queue.info";
    public static String aC = "AVCaptureSessionPreset1280x720";
    public static String aD = "AVCaptureSessionPreset640x480";
    public static int aE = aK;
    public static boolean aF = true;
    public static boolean aG = false;
    public static String aH = "%s_H.iff";
    public static String aI = "%s_H.jpeg";
    public static String aJ = "%s.jpg";
    private static int aK = 3000;
    public static String aa = "mini.jpg";
    public static String ab = "thumb_125x125.jpg";
    public static String ac = "thumb_full.jpg";
    public static String ad = "thumb.jpg";
    public static String ae = "fyuse.magic";
    public static String af = "fyuse_placemark.xml";
    public static String ag = "fyuse_raw.mp4";
    public static String ah = "offsets.dat";
    public static String ai = "motion.dat";
    public static String aj = "progress.dat";
    public static String ak = "fyuse.fyu";
    public static String al = "temp";
    public static String am = "os_magic.dat";
    public static String an = "isd_magic.dat";
    public static String ao = "tween.magic";
    public static String ap = "fyuse_h264_slice";
    public static String aq = (ap + "%s.mp4");
    public static String ar = "fyuse_mjpeg.mp4";
    public static String as = "fyuse_mjpeg.idx";
    public static String at = ".iff";
    public static String au = "fyuse_dropped_frames.dat";
    public static String av = "fyuse_mjpeg";
    public static String aw = "fyuse_h264.mp4";
    public static String ax = "fyuse_h264";
    public static String ay = "fyuse_export_";
    public static String az = "fyuse_h264_%d.mp4";
    public static n b = new n(1920, 1080);
    public static n c = new n(1280, 720);
    public static n d = new n(1136, 640);
    public static e e = new e(1280.0d, 720.0d);
    public static e f = new e(1280.0d, 720.0d);
    public static e g = new e(1136.0d, 640.0d);
    public static e h = new e(3840.0d, 2160.0d);
    public static int i = 10;
    public static int j = 15;
    public static int k = 15;
    public static int l = 15000000;
    public static int m = 3145728;
    public static int n = 10485760;
    public static e o = new e(1920.0d, 1088.0d);
    public static e p = new e(1280.0d, 720.0d);
    public static int q = 5;
    public static float r = 0.01f;
    public static int s = 100;
    public static boolean t = true;
    public static float u = 1.0f;
    public static float v = 0.1f;
    public static float w = 0.1f;
    public static float x = 0.2f;
    public static float y = 0.1f;
    public static float z = 0.75f;

    static {
        System.loadLibrary("vislib_jni");
    }
}
