package com.huawei.device.connectivitychrlog;

public class CSegEVENT_WIFI_STABILITY_STAT extends ChrLogBaseEventModel {
    public ENCEventId enEventId = new ENCEventId();
    public LogInt iCloseCount = new LogInt();
    public LogInt iCloseDuration = new LogInt();
    public LogInt iCloseSuccCount = new LogInt();
    public LogInt iDnsMaxTime = new LogInt();
    public LogInt iDnsMinTime = new LogInt();
    public LogInt iDnsReqCnt = new LogInt();
    public LogInt iDnsReqFail = new LogInt();
    public LogInt iDnsTotTime = new LogInt();
    public LogInt iOpenCount = new LogInt();
    public LogInt iOpenDuration = new LogInt();
    public LogInt iOpenSuccCount = new LogInt();
    public LogInt iRepeaterWorkDuration = new LogInt();
    public LogInt iRepeterConnFailedCount = new LogInt();
    public LogInt iRepeterDiffFreqWorkDuration = new LogInt();
    public LogInt iRepeterOpenSuccCount = new LogInt();
    public LogLong lMobileTotalConnectedDuration = new LogLong();
    public LogLong lMobileTotalTrafficBytes = new LogLong();
    public LogLong lWlanTotalConnectedDuration = new LogLong();
    public LogLong lWlanTotalTrafficBytes = new LogLong();
    public LogDate tmTimeStamp = new LogDate(6);
    public LogByte ucCardIndex = new LogByte();
    public LogByte ucIsMobleAP = new LogByte();
    public LogByte ucRepeterClientMaxCount = new LogByte();
    public LogByte ucScanAlwaysAvailble = new LogByte();
    public LogByte ucWIFIAlwaysNotifation = new LogByte();
    public LogByte ucWIFISleepPolicy = new LogByte();
    public LogByte ucWifiProStatus = new LogByte();
    public LogByte ucWifiToPDP = new LogByte();
    public LogShort usLen = new LogShort();

    public CSegEVENT_WIFI_STABILITY_STAT() {
        this.lengthMap.put("enEventId", Integer.valueOf(1));
        this.fieldMap.put("enEventId", this.enEventId);
        this.lengthMap.put("usLen", Integer.valueOf(2));
        this.fieldMap.put("usLen", this.usLen);
        this.lengthMap.put("tmTimeStamp", Integer.valueOf(6));
        this.fieldMap.put("tmTimeStamp", this.tmTimeStamp);
        this.lengthMap.put("ucCardIndex", Integer.valueOf(1));
        this.fieldMap.put("ucCardIndex", this.ucCardIndex);
        this.lengthMap.put("iOpenCount", Integer.valueOf(4));
        this.fieldMap.put("iOpenCount", this.iOpenCount);
        this.lengthMap.put("iOpenSuccCount", Integer.valueOf(4));
        this.fieldMap.put("iOpenSuccCount", this.iOpenSuccCount);
        this.lengthMap.put("iCloseCount", Integer.valueOf(4));
        this.fieldMap.put("iCloseCount", this.iCloseCount);
        this.lengthMap.put("iCloseSuccCount", Integer.valueOf(4));
        this.fieldMap.put("iCloseSuccCount", this.iCloseSuccCount);
        this.lengthMap.put("iOpenDuration", Integer.valueOf(4));
        this.fieldMap.put("iOpenDuration", this.iOpenDuration);
        this.lengthMap.put("iCloseDuration", Integer.valueOf(4));
        this.fieldMap.put("iCloseDuration", this.iCloseDuration);
        this.lengthMap.put("lWlanTotalTrafficBytes", Integer.valueOf(8));
        this.fieldMap.put("lWlanTotalTrafficBytes", this.lWlanTotalTrafficBytes);
        this.lengthMap.put("lMobileTotalTrafficBytes", Integer.valueOf(8));
        this.fieldMap.put("lMobileTotalTrafficBytes", this.lMobileTotalTrafficBytes);
        this.lengthMap.put("lWlanTotalConnectedDuration", Integer.valueOf(8));
        this.fieldMap.put("lWlanTotalConnectedDuration", this.lWlanTotalConnectedDuration);
        this.lengthMap.put("lMobileTotalConnectedDuration", Integer.valueOf(8));
        this.fieldMap.put("lMobileTotalConnectedDuration", this.lMobileTotalConnectedDuration);
        this.lengthMap.put("ucScanAlwaysAvailble", Integer.valueOf(1));
        this.fieldMap.put("ucScanAlwaysAvailble", this.ucScanAlwaysAvailble);
        this.lengthMap.put("ucWIFIAlwaysNotifation", Integer.valueOf(1));
        this.fieldMap.put("ucWIFIAlwaysNotifation", this.ucWIFIAlwaysNotifation);
        this.lengthMap.put("ucWIFISleepPolicy", Integer.valueOf(1));
        this.fieldMap.put("ucWIFISleepPolicy", this.ucWIFISleepPolicy);
        this.lengthMap.put("ucWifiProStatus", Integer.valueOf(1));
        this.fieldMap.put("ucWifiProStatus", this.ucWifiProStatus);
        this.lengthMap.put("ucWifiToPDP", Integer.valueOf(1));
        this.fieldMap.put("ucWifiToPDP", this.ucWifiToPDP);
        this.lengthMap.put("ucIsMobleAP", Integer.valueOf(1));
        this.fieldMap.put("ucIsMobleAP", this.ucIsMobleAP);
        this.lengthMap.put("iDnsReqCnt", Integer.valueOf(4));
        this.fieldMap.put("iDnsReqCnt", this.iDnsReqCnt);
        this.lengthMap.put("iDnsReqFail", Integer.valueOf(4));
        this.fieldMap.put("iDnsReqFail", this.iDnsReqFail);
        this.lengthMap.put("iDnsMaxTime", Integer.valueOf(4));
        this.fieldMap.put("iDnsMaxTime", this.iDnsMaxTime);
        this.lengthMap.put("iDnsMinTime", Integer.valueOf(4));
        this.fieldMap.put("iDnsMinTime", this.iDnsMinTime);
        this.lengthMap.put("iDnsTotTime", Integer.valueOf(4));
        this.fieldMap.put("iDnsTotTime", this.iDnsTotTime);
        this.lengthMap.put("iRepeaterWorkDuration", Integer.valueOf(4));
        this.fieldMap.put("iRepeaterWorkDuration", this.iRepeaterWorkDuration);
        this.lengthMap.put("iRepeterDiffFreqWorkDuration", Integer.valueOf(4));
        this.fieldMap.put("iRepeterDiffFreqWorkDuration", this.iRepeterDiffFreqWorkDuration);
        this.lengthMap.put("iRepeterOpenSuccCount", Integer.valueOf(4));
        this.fieldMap.put("iRepeterOpenSuccCount", this.iRepeterOpenSuccCount);
        this.lengthMap.put("ucRepeterClientMaxCount", Integer.valueOf(1));
        this.fieldMap.put("ucRepeterClientMaxCount", this.ucRepeterClientMaxCount);
        this.lengthMap.put("iRepeterConnFailedCount", Integer.valueOf(4));
        this.fieldMap.put("iRepeterConnFailedCount", this.iRepeterConnFailedCount);
        this.enEventId.setValue("WIFI_STABILITY_STAT");
        this.usLen.setValue(getTotalLen());
    }
}
