package com.huawei.device.connectivitychrlog;

public class CSegEVENT_WIFI_WIFIPRO_STATISTICS_EVENT extends ChrLogBaseEventModel {
    public ENCEventId enEventId = new ENCEventId();
    public ENCWifiUserType enWifiUserType = new ENCWifiUserType();
    public LogInt iAutoRI_TotTime = new LogInt();
    public LogInt iEnableTotTime = new LogInt();
    public LogInt iHistoryTotWifiConnHour = new LogInt();
    public LogInt iManualRI_TotTime = new LogInt();
    public LogInt iNotInetRO_DISCONNECT_TotData = new LogInt();
    public LogInt iNotInet_AutoRI_TotData = new LogInt();
    public LogInt iQOE_AutoRI_TotData = new LogInt();
    public LogInt iQOE_RO_DISCONNECT_TotData = new LogInt();
    public LogInt iRO_TotMobileData = new LogInt();
    public LogInt iStatIntervalTime = new LogInt();
    public LogInt iTotWifiConnectTime = new LogInt();
    public LogDate tmTimeStamp = new LogDate(6);
    public LogByte ucCardIndex = new LogByte();
    public LogByte ucManualConnBlockPortalCount = new LogByte();
    public LogByte ucWifiproCloseCount = new LogByte();
    public LogByte ucWifiproOpenCount = new LogByte();
    public LogByte ucWifiproStateAtReportTime = new LogByte();
    public LogShort usAF_AutoLoginFailCnt = new LogShort();
    public LogShort usAF_AutoLoginSuccCnt = new LogShort();
    public LogShort usAF_FPNSuccNotMsmCnt = new LogShort();
    public LogShort usAF_PasswordFailCnt = new LogShort();
    public LogShort usAF_PasswordSuccCnt = new LogShort();
    public LogShort usAF_PhoneNumFailCnt = new LogShort();
    public LogShort usAF_PhoneNumSuccCnt = new LogShort();
    public LogShort usActiveCheckRS_Diff = new LogShort();
    public LogShort usActiveCheckRS_Same = new LogShort();
    public LogShort usAutoRI_TotCount = new LogShort();
    public LogShort usBG_AUTH_FailCnt = new LogShort();
    public LogShort usBG_AssocRejectCnt = new LogShort();
    public LogShort usBG_BgRunCnt = new LogShort();
    public LogShort usBG_ConntTimeoutCnt = new LogShort();
    public LogShort usBG_DHCPFailCnt = new LogShort();
    public LogShort usBG_DNSFailCnt = new LogShort();
    public LogShort usBG_FailedCnt = new LogShort();
    public LogShort usBG_FishingApCnt = new LogShort();
    public LogShort usBG_FoundTwoMoreApCnt = new LogShort();
    public LogShort usBG_FreeInetOkApCnt = new LogShort();
    public LogShort usBG_FreeNotInetApCnt = new LogShort();
    public LogShort usBG_InetNotOkActiveOk = new LogShort();
    public LogShort usBG_InetOkActiveNotOk = new LogShort();
    public LogShort usBG_NCByCheckFail = new LogShort();
    public LogShort usBG_NCByConnectFail = new LogShort();
    public LogShort usBG_NCByStateErr = new LogShort();
    public LogShort usBG_NCByUnknown = new LogShort();
    public LogShort usBG_PortalApCnt = new LogShort();
    public LogShort usBG_SettingRunCnt = new LogShort();
    public LogShort usBG_UserSelApFishingCnt = new LogShort();
    public LogShort usBG_UserSelFreeInetOkCnt = new LogShort();
    public LogShort usBG_UserSelNoInetCnt = new LogShort();
    public LogShort usBG_UserSelPortalCnt = new LogShort();
    public LogShort usBMD_FiftyMNotifyCount = new LogShort();
    public LogShort usBMD_FiftyM_RI_Count = new LogShort();
    public LogShort usBMD_TenMNotifyCount = new LogShort();
    public LogShort usBMD_TenM_RI_Count = new LogShort();
    public LogShort usBMD_UserDelNotifyCount = new LogShort();
    public LogShort usBQE_BadSettingCancel = new LogShort();
    public LogShort usBQE_BindWlanFailCount = new LogShort();
    public LogShort usBQE_CNUrl1FailCount = new LogShort();
    public LogShort usBQE_CNUrl2FailCount = new LogShort();
    public LogShort usBQE_CNUrl3FailCount = new LogShort();
    public LogShort usBQE_NCNUrl1FailCount = new LogShort();
    public LogShort usBQE_NCNUrl2FailCount = new LogShort();
    public LogShort usBQE_NCNUrl3FailCount = new LogShort();
    public LogShort usBQE_ScoreUnknownCount = new LogShort();
    public LogShort usBQE_StopBqeFailCount = new LogShort();
    public LogShort usBSG_EndIn4s7sCnt = new LogShort();
    public LogShort usBSG_EndIn4sCnt = new LogShort();
    public LogShort usBSG_NotEndIn7sCnt = new LogShort();
    public LogShort usBSG_RsBadCnt = new LogShort();
    public LogShort usBSG_RsGoodCnt = new LogShort();
    public LogShort usBSG_RsMidCnt = new LogShort();
    public LogShort usBigRTT_ErrRO_Tot = new LogShort();
    public LogShort usBigRTT_RO_Tot = new LogShort();
    public LogShort usCellAutoCloseCount = new LogShort();
    public LogShort usCellAutoOpenCount = new LogShort();
    public LogShort usCustomizedScan_FailCount = new LogShort();
    public LogShort usCustomizedScan_SuccCount = new LogShort();
    public LogShort usHandoverPingpongCount = new LogShort();
    public LogShort usHandoverToBad5GCount = new LogShort();
    public LogShort usHandoverToNotInet5GCount = new LogShort();
    public LogShort usHandoverTooSlowCount = new LogShort();
    public LogShort usHighDataRateStopROC = new LogShort();
    public LogShort usHisScoRI_Count = new LogShort();
    public LogShort usHomeAPAddRoPeriodCnt = new LogShort();
    public LogShort usHomeAPQoeBadCnt = new LogShort();
    public LogShort usLen = new LogShort();
    public LogShort usManualBackROC = new LogShort();
    public LogShort usMixedAP_DisapperCount = new LogShort();
    public LogShort usMixedAP_HandoverFailCount = new LogShort();
    public LogShort usMixedAP_HandoverSucCount = new LogShort();
    public LogShort usMixedAP_HighFreqScan5GCount = new LogShort();
    public LogShort usMixedAP_InblacklistCount = new LogShort();
    public LogShort usMixedAP_LearnedCount = new LogShort();
    public LogShort usMixedAP_LowFreqScan5GCount = new LogShort();
    public LogShort usMixedAP_MidFreqScan5GCount = new LogShort();
    public LogShort usMixedAP_MonitorCount = new LogShort();
    public LogShort usMixedAP_NearbyCount = new LogShort();
    public LogShort usMixedAP_SatisfiedCount = new LogShort();
    public LogShort usMixedAP_ScoreNotSatisfyCount = new LogShort();
    public LogShort usNoInetAlarmCount = new LogShort();
    public LogShort usNoInetAlarmOnConnCnt = new LogShort();
    public LogShort usNoInetHandoverCount = new LogShort();
    public LogShort usNotAutoConnPortalCnt = new LogShort();
    public LogShort usNotInetRO_DISCONNECT_Cnt = new LogShort();
    public LogShort usNotInetRestoreRI = new LogShort();
    public LogShort usNotInetSettingCancel = new LogShort();
    public LogShort usNotInetUserCancel = new LogShort();
    public LogShort usNotInetUserManualRI = new LogShort();
    public LogShort usNotInetWifiToWifiCount = new LogShort();
    public LogShort usOTA_ErrRO_Tot = new LogShort();
    public LogShort usOTA_RO_Tot = new LogShort();
    public LogShort usPingPongCount = new LogShort();
    public LogShort usPortalAutoLoginCount = new LogShort();
    public LogShort usPortalCodeParseCount = new LogShort();
    public LogShort usPortalNoAutoConnCnt = new LogShort();
    public LogShort usPortalUnauthCount = new LogShort();
    public LogShort usQOE_RO_DISCONNECT_Cnt = new LogShort();
    public LogShort usRSSI_BetterRI_Count = new LogShort();
    public LogShort usRSSI_ErrRO_Tot = new LogShort();
    public LogShort usRSSI_RO_Tot = new LogShort();
    public LogShort usRSSI_RestoreRI_Count = new LogShort();
    public LogShort usRcvSMS_Count = new LogShort();
    public LogShort usReopenWifiRICount = new LogShort();
    public LogShort usSelCSPAutoSwCount = new LogShort();
    public LogShort usSelCSPNotSwCount = new LogShort();
    public LogShort usSelCSPShowDiglogCount = new LogShort();
    public LogShort usSelectNotInetAPCount = new LogShort();
    public LogShort usSingleAP_DisapperCount = new LogShort();
    public LogShort usSingleAP_HandoverFailCount = new LogShort();
    public LogShort usSingleAP_HandoverSucCount = new LogShort();
    public LogShort usSingleAP_HighFreqScan5GCount = new LogShort();
    public LogShort usSingleAP_InblacklistCount = new LogShort();
    public LogShort usSingleAP_LearnedCount = new LogShort();
    public LogShort usSingleAP_LowFreqScan5GCount = new LogShort();
    public LogShort usSingleAP_MidFreqScan5GCount = new LogShort();
    public LogShort usSingleAP_MonitorCount = new LogShort();
    public LogShort usSingleAP_NearbyCount = new LogShort();
    public LogShort usSingleAP_SatisfiedCount = new LogShort();
    public LogShort usSingleAP_ScoreNotSatisfyCount = new LogShort();
    public LogShort usTCP_ErrRO_Tot = new LogShort();
    public LogShort usTCP_RO_Tot = new LogShort();
    public LogShort usTimerRI_Count = new LogShort();
    public LogShort usTotAPRecordCnt = new LogShort();
    public LogShort usTotBtnRICount = new LogShort();
    public LogShort usTotHomeAPCnt = new LogShort();
    public LogShort usTotalBQE_BadROC = new LogShort();
    public LogShort usTotalPortalAuthSuccCount = new LogShort();
    public LogShort usTotalPortalConnCount = new LogShort();
    public LogShort usUserCancelROC = new LogShort();
    public LogShort usUserRejectHandoverCount = new LogShort();
    public LogShort usUserUseBgScanAPCount = new LogShort();
    public LogShort usWifiOobInitState = new LogShort();
    public LogShort usWifiScoCount = new LogShort();
    public LogShort usWifiToWifiSuccCount = new LogShort();

    public CSegEVENT_WIFI_WIFIPRO_STATISTICS_EVENT() {
        this.lengthMap.put("enEventId", Integer.valueOf(1));
        this.fieldMap.put("enEventId", this.enEventId);
        this.lengthMap.put("usLen", Integer.valueOf(2));
        this.fieldMap.put("usLen", this.usLen);
        this.lengthMap.put("tmTimeStamp", Integer.valueOf(6));
        this.fieldMap.put("tmTimeStamp", this.tmTimeStamp);
        this.lengthMap.put("ucCardIndex", Integer.valueOf(1));
        this.fieldMap.put("ucCardIndex", this.ucCardIndex);
        this.lengthMap.put("enWifiUserType", Integer.valueOf(1));
        this.fieldMap.put("enWifiUserType", this.enWifiUserType);
        this.lengthMap.put("iStatIntervalTime", Integer.valueOf(4));
        this.fieldMap.put("iStatIntervalTime", this.iStatIntervalTime);
        this.lengthMap.put("iEnableTotTime", Integer.valueOf(4));
        this.fieldMap.put("iEnableTotTime", this.iEnableTotTime);
        this.lengthMap.put("usWifiOobInitState", Integer.valueOf(2));
        this.fieldMap.put("usWifiOobInitState", this.usWifiOobInitState);
        this.lengthMap.put("usPortalUnauthCount", Integer.valueOf(2));
        this.fieldMap.put("usPortalUnauthCount", this.usPortalUnauthCount);
        this.lengthMap.put("usWifiScoCount", Integer.valueOf(2));
        this.fieldMap.put("usWifiScoCount", this.usWifiScoCount);
        this.lengthMap.put("usPortalCodeParseCount", Integer.valueOf(2));
        this.fieldMap.put("usPortalCodeParseCount", this.usPortalCodeParseCount);
        this.lengthMap.put("usRcvSMS_Count", Integer.valueOf(2));
        this.fieldMap.put("usRcvSMS_Count", this.usRcvSMS_Count);
        this.lengthMap.put("usNoInetAlarmCount", Integer.valueOf(2));
        this.fieldMap.put("usNoInetAlarmCount", this.usNoInetAlarmCount);
        this.lengthMap.put("usUserUseBgScanAPCount", Integer.valueOf(2));
        this.fieldMap.put("usUserUseBgScanAPCount", this.usUserUseBgScanAPCount);
        this.lengthMap.put("usWifiToWifiSuccCount", Integer.valueOf(2));
        this.fieldMap.put("usWifiToWifiSuccCount", this.usWifiToWifiSuccCount);
        this.lengthMap.put("usNoInetHandoverCount", Integer.valueOf(2));
        this.fieldMap.put("usNoInetHandoverCount", this.usNoInetHandoverCount);
        this.lengthMap.put("usTotalBQE_BadROC", Integer.valueOf(2));
        this.fieldMap.put("usTotalBQE_BadROC", this.usTotalBQE_BadROC);
        this.lengthMap.put("usManualBackROC", Integer.valueOf(2));
        this.fieldMap.put("usManualBackROC", this.usManualBackROC);
        this.lengthMap.put("usUserCancelROC", Integer.valueOf(2));
        this.fieldMap.put("usUserCancelROC", this.usUserCancelROC);
        this.lengthMap.put("usRSSI_RO_Tot", Integer.valueOf(2));
        this.fieldMap.put("usRSSI_RO_Tot", this.usRSSI_RO_Tot);
        this.lengthMap.put("usRSSI_ErrRO_Tot", Integer.valueOf(2));
        this.fieldMap.put("usRSSI_ErrRO_Tot", this.usRSSI_ErrRO_Tot);
        this.lengthMap.put("usOTA_RO_Tot", Integer.valueOf(2));
        this.fieldMap.put("usOTA_RO_Tot", this.usOTA_RO_Tot);
        this.lengthMap.put("usOTA_ErrRO_Tot", Integer.valueOf(2));
        this.fieldMap.put("usOTA_ErrRO_Tot", this.usOTA_ErrRO_Tot);
        this.lengthMap.put("usTCP_RO_Tot", Integer.valueOf(2));
        this.fieldMap.put("usTCP_RO_Tot", this.usTCP_RO_Tot);
        this.lengthMap.put("usTCP_ErrRO_Tot", Integer.valueOf(2));
        this.fieldMap.put("usTCP_ErrRO_Tot", this.usTCP_ErrRO_Tot);
        this.lengthMap.put("iManualRI_TotTime", Integer.valueOf(4));
        this.fieldMap.put("iManualRI_TotTime", this.iManualRI_TotTime);
        this.lengthMap.put("iAutoRI_TotTime", Integer.valueOf(4));
        this.fieldMap.put("iAutoRI_TotTime", this.iAutoRI_TotTime);
        this.lengthMap.put("usAutoRI_TotCount", Integer.valueOf(2));
        this.fieldMap.put("usAutoRI_TotCount", this.usAutoRI_TotCount);
        this.lengthMap.put("usRSSI_RestoreRI_Count", Integer.valueOf(2));
        this.fieldMap.put("usRSSI_RestoreRI_Count", this.usRSSI_RestoreRI_Count);
        this.lengthMap.put("usRSSI_BetterRI_Count", Integer.valueOf(2));
        this.fieldMap.put("usRSSI_BetterRI_Count", this.usRSSI_BetterRI_Count);
        this.lengthMap.put("usTimerRI_Count", Integer.valueOf(2));
        this.fieldMap.put("usTimerRI_Count", this.usTimerRI_Count);
        this.lengthMap.put("usHisScoRI_Count", Integer.valueOf(2));
        this.fieldMap.put("usHisScoRI_Count", this.usHisScoRI_Count);
        this.lengthMap.put("usHighDataRateStopROC", Integer.valueOf(2));
        this.fieldMap.put("usHighDataRateStopROC", this.usHighDataRateStopROC);
        this.lengthMap.put("usSelectNotInetAPCount", Integer.valueOf(2));
        this.fieldMap.put("usSelectNotInetAPCount", this.usSelectNotInetAPCount);
        this.lengthMap.put("usPortalAutoLoginCount", Integer.valueOf(2));
        this.fieldMap.put("usPortalAutoLoginCount", this.usPortalAutoLoginCount);
        this.lengthMap.put("usNotAutoConnPortalCnt", Integer.valueOf(2));
        this.fieldMap.put("usNotAutoConnPortalCnt", this.usNotAutoConnPortalCnt);
        this.lengthMap.put("usCellAutoOpenCount", Integer.valueOf(2));
        this.fieldMap.put("usCellAutoOpenCount", this.usCellAutoOpenCount);
        this.lengthMap.put("usCellAutoCloseCount", Integer.valueOf(2));
        this.fieldMap.put("usCellAutoCloseCount", this.usCellAutoCloseCount);
        this.lengthMap.put("usPingPongCount", Integer.valueOf(2));
        this.fieldMap.put("usPingPongCount", this.usPingPongCount);
        this.lengthMap.put("usBQE_BadSettingCancel", Integer.valueOf(2));
        this.fieldMap.put("usBQE_BadSettingCancel", this.usBQE_BadSettingCancel);
        this.lengthMap.put("usNotInetSettingCancel", Integer.valueOf(2));
        this.fieldMap.put("usNotInetSettingCancel", this.usNotInetSettingCancel);
        this.lengthMap.put("usNotInetUserCancel", Integer.valueOf(2));
        this.fieldMap.put("usNotInetUserCancel", this.usNotInetUserCancel);
        this.lengthMap.put("usNotInetRestoreRI", Integer.valueOf(2));
        this.fieldMap.put("usNotInetRestoreRI", this.usNotInetRestoreRI);
        this.lengthMap.put("usNotInetUserManualRI", Integer.valueOf(2));
        this.fieldMap.put("usNotInetUserManualRI", this.usNotInetUserManualRI);
        this.lengthMap.put("usNotInetWifiToWifiCount", Integer.valueOf(2));
        this.fieldMap.put("usNotInetWifiToWifiCount", this.usNotInetWifiToWifiCount);
        this.lengthMap.put("usReopenWifiRICount", Integer.valueOf(2));
        this.fieldMap.put("usReopenWifiRICount", this.usReopenWifiRICount);
        this.lengthMap.put("usSelCSPShowDiglogCount", Integer.valueOf(2));
        this.fieldMap.put("usSelCSPShowDiglogCount", this.usSelCSPShowDiglogCount);
        this.lengthMap.put("usSelCSPAutoSwCount", Integer.valueOf(2));
        this.fieldMap.put("usSelCSPAutoSwCount", this.usSelCSPAutoSwCount);
        this.lengthMap.put("usSelCSPNotSwCount", Integer.valueOf(2));
        this.fieldMap.put("usSelCSPNotSwCount", this.usSelCSPNotSwCount);
        this.lengthMap.put("usTotBtnRICount", Integer.valueOf(2));
        this.fieldMap.put("usTotBtnRICount", this.usTotBtnRICount);
        this.lengthMap.put("usBMD_TenMNotifyCount", Integer.valueOf(2));
        this.fieldMap.put("usBMD_TenMNotifyCount", this.usBMD_TenMNotifyCount);
        this.lengthMap.put("usBMD_TenM_RI_Count", Integer.valueOf(2));
        this.fieldMap.put("usBMD_TenM_RI_Count", this.usBMD_TenM_RI_Count);
        this.lengthMap.put("usBMD_FiftyMNotifyCount", Integer.valueOf(2));
        this.fieldMap.put("usBMD_FiftyMNotifyCount", this.usBMD_FiftyMNotifyCount);
        this.lengthMap.put("usBMD_FiftyM_RI_Count", Integer.valueOf(2));
        this.fieldMap.put("usBMD_FiftyM_RI_Count", this.usBMD_FiftyM_RI_Count);
        this.lengthMap.put("usBMD_UserDelNotifyCount", Integer.valueOf(2));
        this.fieldMap.put("usBMD_UserDelNotifyCount", this.usBMD_UserDelNotifyCount);
        this.lengthMap.put("iRO_TotMobileData", Integer.valueOf(4));
        this.fieldMap.put("iRO_TotMobileData", this.iRO_TotMobileData);
        this.lengthMap.put("usAF_PhoneNumSuccCnt", Integer.valueOf(2));
        this.fieldMap.put("usAF_PhoneNumSuccCnt", this.usAF_PhoneNumSuccCnt);
        this.lengthMap.put("usAF_PhoneNumFailCnt", Integer.valueOf(2));
        this.fieldMap.put("usAF_PhoneNumFailCnt", this.usAF_PhoneNumFailCnt);
        this.lengthMap.put("usAF_PasswordSuccCnt", Integer.valueOf(2));
        this.fieldMap.put("usAF_PasswordSuccCnt", this.usAF_PasswordSuccCnt);
        this.lengthMap.put("usAF_PasswordFailCnt", Integer.valueOf(2));
        this.fieldMap.put("usAF_PasswordFailCnt", this.usAF_PasswordFailCnt);
        this.lengthMap.put("usAF_AutoLoginSuccCnt", Integer.valueOf(2));
        this.fieldMap.put("usAF_AutoLoginSuccCnt", this.usAF_AutoLoginSuccCnt);
        this.lengthMap.put("usAF_AutoLoginFailCnt", Integer.valueOf(2));
        this.fieldMap.put("usAF_AutoLoginFailCnt", this.usAF_AutoLoginFailCnt);
        this.lengthMap.put("usAF_FPNSuccNotMsmCnt", Integer.valueOf(2));
        this.fieldMap.put("usAF_FPNSuccNotMsmCnt", this.usAF_FPNSuccNotMsmCnt);
        this.lengthMap.put("usBSG_RsGoodCnt", Integer.valueOf(2));
        this.fieldMap.put("usBSG_RsGoodCnt", this.usBSG_RsGoodCnt);
        this.lengthMap.put("usBSG_RsMidCnt", Integer.valueOf(2));
        this.fieldMap.put("usBSG_RsMidCnt", this.usBSG_RsMidCnt);
        this.lengthMap.put("usBSG_RsBadCnt", Integer.valueOf(2));
        this.fieldMap.put("usBSG_RsBadCnt", this.usBSG_RsBadCnt);
        this.lengthMap.put("usBSG_EndIn4sCnt", Integer.valueOf(2));
        this.fieldMap.put("usBSG_EndIn4sCnt", this.usBSG_EndIn4sCnt);
        this.lengthMap.put("usBSG_EndIn4s7sCnt", Integer.valueOf(2));
        this.fieldMap.put("usBSG_EndIn4s7sCnt", this.usBSG_EndIn4s7sCnt);
        this.lengthMap.put("usBSG_NotEndIn7sCnt", Integer.valueOf(2));
        this.fieldMap.put("usBSG_NotEndIn7sCnt", this.usBSG_NotEndIn7sCnt);
        this.lengthMap.put("usBG_BgRunCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_BgRunCnt", this.usBG_BgRunCnt);
        this.lengthMap.put("usBG_SettingRunCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_SettingRunCnt", this.usBG_SettingRunCnt);
        this.lengthMap.put("usBG_FreeInetOkApCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_FreeInetOkApCnt", this.usBG_FreeInetOkApCnt);
        this.lengthMap.put("usBG_FishingApCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_FishingApCnt", this.usBG_FishingApCnt);
        this.lengthMap.put("usBG_FreeNotInetApCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_FreeNotInetApCnt", this.usBG_FreeNotInetApCnt);
        this.lengthMap.put("usBG_PortalApCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_PortalApCnt", this.usBG_PortalApCnt);
        this.lengthMap.put("usBG_UserSelFreeInetOkCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_UserSelFreeInetOkCnt", this.usBG_UserSelFreeInetOkCnt);
        this.lengthMap.put("usBG_UserSelNoInetCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_UserSelNoInetCnt", this.usBG_UserSelNoInetCnt);
        this.lengthMap.put("usBG_UserSelPortalCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_UserSelPortalCnt", this.usBG_UserSelPortalCnt);
        this.lengthMap.put("usBG_FoundTwoMoreApCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_FoundTwoMoreApCnt", this.usBG_FoundTwoMoreApCnt);
        this.lengthMap.put("usBG_FailedCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_FailedCnt", this.usBG_FailedCnt);
        this.lengthMap.put("usBG_InetNotOkActiveOk", Integer.valueOf(2));
        this.fieldMap.put("usBG_InetNotOkActiveOk", this.usBG_InetNotOkActiveOk);
        this.lengthMap.put("usBG_InetOkActiveNotOk", Integer.valueOf(2));
        this.fieldMap.put("usBG_InetOkActiveNotOk", this.usBG_InetOkActiveNotOk);
        this.lengthMap.put("usBG_UserSelApFishingCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_UserSelApFishingCnt", this.usBG_UserSelApFishingCnt);
        this.lengthMap.put("usBG_ConntTimeoutCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_ConntTimeoutCnt", this.usBG_ConntTimeoutCnt);
        this.lengthMap.put("usBG_DNSFailCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_DNSFailCnt", this.usBG_DNSFailCnt);
        this.lengthMap.put("usBG_DHCPFailCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_DHCPFailCnt", this.usBG_DHCPFailCnt);
        this.lengthMap.put("usBG_AUTH_FailCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_AUTH_FailCnt", this.usBG_AUTH_FailCnt);
        this.lengthMap.put("usBG_AssocRejectCnt", Integer.valueOf(2));
        this.fieldMap.put("usBG_AssocRejectCnt", this.usBG_AssocRejectCnt);
        this.lengthMap.put("usBG_NCByConnectFail", Integer.valueOf(2));
        this.fieldMap.put("usBG_NCByConnectFail", this.usBG_NCByConnectFail);
        this.lengthMap.put("usBG_NCByCheckFail", Integer.valueOf(2));
        this.fieldMap.put("usBG_NCByCheckFail", this.usBG_NCByCheckFail);
        this.lengthMap.put("usBG_NCByStateErr", Integer.valueOf(2));
        this.fieldMap.put("usBG_NCByStateErr", this.usBG_NCByStateErr);
        this.lengthMap.put("usBG_NCByUnknown", Integer.valueOf(2));
        this.fieldMap.put("usBG_NCByUnknown", this.usBG_NCByUnknown);
        this.lengthMap.put("usBQE_CNUrl1FailCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_CNUrl1FailCount", this.usBQE_CNUrl1FailCount);
        this.lengthMap.put("usBQE_CNUrl2FailCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_CNUrl2FailCount", this.usBQE_CNUrl2FailCount);
        this.lengthMap.put("usBQE_CNUrl3FailCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_CNUrl3FailCount", this.usBQE_CNUrl3FailCount);
        this.lengthMap.put("usBQE_NCNUrl1FailCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_NCNUrl1FailCount", this.usBQE_NCNUrl1FailCount);
        this.lengthMap.put("usBQE_NCNUrl2FailCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_NCNUrl2FailCount", this.usBQE_NCNUrl2FailCount);
        this.lengthMap.put("usBQE_NCNUrl3FailCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_NCNUrl3FailCount", this.usBQE_NCNUrl3FailCount);
        this.lengthMap.put("usBQE_ScoreUnknownCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_ScoreUnknownCount", this.usBQE_ScoreUnknownCount);
        this.lengthMap.put("usBQE_BindWlanFailCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_BindWlanFailCount", this.usBQE_BindWlanFailCount);
        this.lengthMap.put("usBQE_StopBqeFailCount", Integer.valueOf(2));
        this.fieldMap.put("usBQE_StopBqeFailCount", this.usBQE_StopBqeFailCount);
        this.lengthMap.put("iQOE_AutoRI_TotData", Integer.valueOf(4));
        this.fieldMap.put("iQOE_AutoRI_TotData", this.iQOE_AutoRI_TotData);
        this.lengthMap.put("iNotInet_AutoRI_TotData", Integer.valueOf(4));
        this.fieldMap.put("iNotInet_AutoRI_TotData", this.iNotInet_AutoRI_TotData);
        this.lengthMap.put("usQOE_RO_DISCONNECT_Cnt", Integer.valueOf(2));
        this.fieldMap.put("usQOE_RO_DISCONNECT_Cnt", this.usQOE_RO_DISCONNECT_Cnt);
        this.lengthMap.put("iQOE_RO_DISCONNECT_TotData", Integer.valueOf(4));
        this.fieldMap.put("iQOE_RO_DISCONNECT_TotData", this.iQOE_RO_DISCONNECT_TotData);
        this.lengthMap.put("usNotInetRO_DISCONNECT_Cnt", Integer.valueOf(2));
        this.fieldMap.put("usNotInetRO_DISCONNECT_Cnt", this.usNotInetRO_DISCONNECT_Cnt);
        this.lengthMap.put("iNotInetRO_DISCONNECT_TotData", Integer.valueOf(4));
        this.fieldMap.put("iNotInetRO_DISCONNECT_TotData", this.iNotInetRO_DISCONNECT_TotData);
        this.lengthMap.put("iTotWifiConnectTime", Integer.valueOf(4));
        this.fieldMap.put("iTotWifiConnectTime", this.iTotWifiConnectTime);
        this.lengthMap.put("usActiveCheckRS_Diff", Integer.valueOf(2));
        this.fieldMap.put("usActiveCheckRS_Diff", this.usActiveCheckRS_Diff);
        this.lengthMap.put("usNoInetAlarmOnConnCnt", Integer.valueOf(2));
        this.fieldMap.put("usNoInetAlarmOnConnCnt", this.usNoInetAlarmOnConnCnt);
        this.lengthMap.put("usPortalNoAutoConnCnt", Integer.valueOf(2));
        this.fieldMap.put("usPortalNoAutoConnCnt", this.usPortalNoAutoConnCnt);
        this.lengthMap.put("usHomeAPAddRoPeriodCnt", Integer.valueOf(2));
        this.fieldMap.put("usHomeAPAddRoPeriodCnt", this.usHomeAPAddRoPeriodCnt);
        this.lengthMap.put("usHomeAPQoeBadCnt", Integer.valueOf(2));
        this.fieldMap.put("usHomeAPQoeBadCnt", this.usHomeAPQoeBadCnt);
        this.lengthMap.put("usTotAPRecordCnt", Integer.valueOf(2));
        this.fieldMap.put("usTotAPRecordCnt", this.usTotAPRecordCnt);
        this.lengthMap.put("usTotHomeAPCnt", Integer.valueOf(2));
        this.fieldMap.put("usTotHomeAPCnt", this.usTotHomeAPCnt);
        this.lengthMap.put("iHistoryTotWifiConnHour", Integer.valueOf(4));
        this.fieldMap.put("iHistoryTotWifiConnHour", this.iHistoryTotWifiConnHour);
        this.lengthMap.put("usBigRTT_RO_Tot", Integer.valueOf(2));
        this.fieldMap.put("usBigRTT_RO_Tot", this.usBigRTT_RO_Tot);
        this.lengthMap.put("usBigRTT_ErrRO_Tot", Integer.valueOf(2));
        this.fieldMap.put("usBigRTT_ErrRO_Tot", this.usBigRTT_ErrRO_Tot);
        this.lengthMap.put("usTotalPortalConnCount", Integer.valueOf(2));
        this.fieldMap.put("usTotalPortalConnCount", this.usTotalPortalConnCount);
        this.lengthMap.put("usTotalPortalAuthSuccCount", Integer.valueOf(2));
        this.fieldMap.put("usTotalPortalAuthSuccCount", this.usTotalPortalAuthSuccCount);
        this.lengthMap.put("ucManualConnBlockPortalCount", Integer.valueOf(1));
        this.fieldMap.put("ucManualConnBlockPortalCount", this.ucManualConnBlockPortalCount);
        this.lengthMap.put("ucWifiproStateAtReportTime", Integer.valueOf(1));
        this.fieldMap.put("ucWifiproStateAtReportTime", this.ucWifiproStateAtReportTime);
        this.lengthMap.put("ucWifiproOpenCount", Integer.valueOf(1));
        this.fieldMap.put("ucWifiproOpenCount", this.ucWifiproOpenCount);
        this.lengthMap.put("ucWifiproCloseCount", Integer.valueOf(1));
        this.fieldMap.put("ucWifiproCloseCount", this.ucWifiproCloseCount);
        this.lengthMap.put("usActiveCheckRS_Same", Integer.valueOf(2));
        this.fieldMap.put("usActiveCheckRS_Same", this.usActiveCheckRS_Same);
        this.lengthMap.put("usSingleAP_LearnedCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_LearnedCount", this.usSingleAP_LearnedCount);
        this.lengthMap.put("usSingleAP_NearbyCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_NearbyCount", this.usSingleAP_NearbyCount);
        this.lengthMap.put("usSingleAP_MonitorCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_MonitorCount", this.usSingleAP_MonitorCount);
        this.lengthMap.put("usSingleAP_SatisfiedCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_SatisfiedCount", this.usSingleAP_SatisfiedCount);
        this.lengthMap.put("usSingleAP_DisapperCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_DisapperCount", this.usSingleAP_DisapperCount);
        this.lengthMap.put("usSingleAP_InblacklistCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_InblacklistCount", this.usSingleAP_InblacklistCount);
        this.lengthMap.put("usSingleAP_ScoreNotSatisfyCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_ScoreNotSatisfyCount", this.usSingleAP_ScoreNotSatisfyCount);
        this.lengthMap.put("usSingleAP_HandoverSucCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_HandoverSucCount", this.usSingleAP_HandoverSucCount);
        this.lengthMap.put("usSingleAP_HandoverFailCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_HandoverFailCount", this.usSingleAP_HandoverFailCount);
        this.lengthMap.put("usSingleAP_LowFreqScan5GCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_LowFreqScan5GCount", this.usSingleAP_LowFreqScan5GCount);
        this.lengthMap.put("usSingleAP_MidFreqScan5GCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_MidFreqScan5GCount", this.usSingleAP_MidFreqScan5GCount);
        this.lengthMap.put("usSingleAP_HighFreqScan5GCount", Integer.valueOf(2));
        this.fieldMap.put("usSingleAP_HighFreqScan5GCount", this.usSingleAP_HighFreqScan5GCount);
        this.lengthMap.put("usMixedAP_LearnedCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_LearnedCount", this.usMixedAP_LearnedCount);
        this.lengthMap.put("usMixedAP_NearbyCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_NearbyCount", this.usMixedAP_NearbyCount);
        this.lengthMap.put("usMixedAP_MonitorCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_MonitorCount", this.usMixedAP_MonitorCount);
        this.lengthMap.put("usMixedAP_SatisfiedCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_SatisfiedCount", this.usMixedAP_SatisfiedCount);
        this.lengthMap.put("usMixedAP_DisapperCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_DisapperCount", this.usMixedAP_DisapperCount);
        this.lengthMap.put("usMixedAP_InblacklistCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_InblacklistCount", this.usMixedAP_InblacklistCount);
        this.lengthMap.put("usMixedAP_ScoreNotSatisfyCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_ScoreNotSatisfyCount", this.usMixedAP_ScoreNotSatisfyCount);
        this.lengthMap.put("usMixedAP_HandoverSucCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_HandoverSucCount", this.usMixedAP_HandoverSucCount);
        this.lengthMap.put("usMixedAP_HandoverFailCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_HandoverFailCount", this.usMixedAP_HandoverFailCount);
        this.lengthMap.put("usMixedAP_LowFreqScan5GCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_LowFreqScan5GCount", this.usMixedAP_LowFreqScan5GCount);
        this.lengthMap.put("usMixedAP_MidFreqScan5GCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_MidFreqScan5GCount", this.usMixedAP_MidFreqScan5GCount);
        this.lengthMap.put("usMixedAP_HighFreqScan5GCount", Integer.valueOf(2));
        this.fieldMap.put("usMixedAP_HighFreqScan5GCount", this.usMixedAP_HighFreqScan5GCount);
        this.lengthMap.put("usCustomizedScan_SuccCount", Integer.valueOf(2));
        this.fieldMap.put("usCustomizedScan_SuccCount", this.usCustomizedScan_SuccCount);
        this.lengthMap.put("usCustomizedScan_FailCount", Integer.valueOf(2));
        this.fieldMap.put("usCustomizedScan_FailCount", this.usCustomizedScan_FailCount);
        this.lengthMap.put("usHandoverToNotInet5GCount", Integer.valueOf(2));
        this.fieldMap.put("usHandoverToNotInet5GCount", this.usHandoverToNotInet5GCount);
        this.lengthMap.put("usHandoverTooSlowCount", Integer.valueOf(2));
        this.fieldMap.put("usHandoverTooSlowCount", this.usHandoverTooSlowCount);
        this.lengthMap.put("usHandoverToBad5GCount", Integer.valueOf(2));
        this.fieldMap.put("usHandoverToBad5GCount", this.usHandoverToBad5GCount);
        this.lengthMap.put("usUserRejectHandoverCount", Integer.valueOf(2));
        this.fieldMap.put("usUserRejectHandoverCount", this.usUserRejectHandoverCount);
        this.lengthMap.put("usHandoverPingpongCount", Integer.valueOf(2));
        this.fieldMap.put("usHandoverPingpongCount", this.usHandoverPingpongCount);
        this.enEventId.setValue("WIFI_WIFIPRO_STATISTICS_EVENT");
        this.usLen.setValue(getTotalLen());
    }
}
