package com.huawei.device.connectivitychrlog;

public class CSegEVENT_WIFI_DAILY_UPLOAD extends ChrLogBaseEventModel {
    public ENCEventId enEventId = new ENCEventId();
    public LogInt iAntSwitchCnt = new LogInt();
    public LogInt iAvgRSSI = new LogInt();
    public LogInt iMainAntTime = new LogInt();
    public LogInt iSecAntTime = new LogInt();
    public LogInt iaccessfailCnt = new LogInt();
    public LogInt iassocrejectCnt = new LogInt();
    public LogInt iauthfailCnt = new LogInt();
    public LogInt iclosefailCnt = new LogInt();
    public LogInt idhcpfailCnt = new LogInt();
    public LogInt idisconnectCnt = new LogInt();
    public LogInt iopenfailCnt = new LogInt();
    public LogInt ireasoncodeCnt1 = new LogInt();
    public LogInt ireasoncodeCnt2 = new LogInt();
    public LogInt ireasoncodeCnt3 = new LogInt();
    public LogInt ireasoncodeCnt4 = new LogInt();
    public LogInt ireasoncodeCnt5 = new LogInt();
    public LogInt ireasoncodeCnt6 = new LogInt();
    public LogInt iscanfailCnt = new LogInt();
    public LogDate tmTimeStamp = new LogDate(6);
    public LogByte ucCardIndex = new LogByte();
    public LogShort usLen = new LogShort();
    public LogShort usSubErrorCode = new LogShort();
    public LogShort usreasoncode1 = new LogShort();
    public LogShort usreasoncode2 = new LogShort();
    public LogShort usreasoncode3 = new LogShort();
    public LogShort usreasoncode4 = new LogShort();
    public LogShort usreasoncode5 = new LogShort();
    public LogShort usreasoncode6 = new LogShort();

    public CSegEVENT_WIFI_DAILY_UPLOAD() {
        this.lengthMap.put("enEventId", Integer.valueOf(1));
        this.fieldMap.put("enEventId", this.enEventId);
        this.lengthMap.put("usLen", Integer.valueOf(2));
        this.fieldMap.put("usLen", this.usLen);
        this.lengthMap.put("tmTimeStamp", Integer.valueOf(6));
        this.fieldMap.put("tmTimeStamp", this.tmTimeStamp);
        this.lengthMap.put("ucCardIndex", Integer.valueOf(1));
        this.fieldMap.put("ucCardIndex", this.ucCardIndex);
        this.lengthMap.put("usSubErrorCode", Integer.valueOf(2));
        this.fieldMap.put("usSubErrorCode", this.usSubErrorCode);
        this.lengthMap.put("iopenfailCnt", Integer.valueOf(4));
        this.fieldMap.put("iopenfailCnt", this.iopenfailCnt);
        this.lengthMap.put("iclosefailCnt", Integer.valueOf(4));
        this.fieldMap.put("iclosefailCnt", this.iclosefailCnt);
        this.lengthMap.put("idhcpfailCnt", Integer.valueOf(4));
        this.fieldMap.put("idhcpfailCnt", this.idhcpfailCnt);
        this.lengthMap.put("iscanfailCnt", Integer.valueOf(4));
        this.fieldMap.put("iscanfailCnt", this.iscanfailCnt);
        this.lengthMap.put("iaccessfailCnt", Integer.valueOf(4));
        this.fieldMap.put("iaccessfailCnt", this.iaccessfailCnt);
        this.lengthMap.put("idisconnectCnt", Integer.valueOf(4));
        this.fieldMap.put("idisconnectCnt", this.idisconnectCnt);
        this.lengthMap.put("iassocrejectCnt", Integer.valueOf(4));
        this.fieldMap.put("iassocrejectCnt", this.iassocrejectCnt);
        this.lengthMap.put("iauthfailCnt", Integer.valueOf(4));
        this.fieldMap.put("iauthfailCnt", this.iauthfailCnt);
        this.lengthMap.put("usreasoncode1", Integer.valueOf(2));
        this.fieldMap.put("usreasoncode1", this.usreasoncode1);
        this.lengthMap.put("ireasoncodeCnt1", Integer.valueOf(4));
        this.fieldMap.put("ireasoncodeCnt1", this.ireasoncodeCnt1);
        this.lengthMap.put("usreasoncode2", Integer.valueOf(2));
        this.fieldMap.put("usreasoncode2", this.usreasoncode2);
        this.lengthMap.put("ireasoncodeCnt2", Integer.valueOf(4));
        this.fieldMap.put("ireasoncodeCnt2", this.ireasoncodeCnt2);
        this.lengthMap.put("usreasoncode3", Integer.valueOf(2));
        this.fieldMap.put("usreasoncode3", this.usreasoncode3);
        this.lengthMap.put("ireasoncodeCnt3", Integer.valueOf(4));
        this.fieldMap.put("ireasoncodeCnt3", this.ireasoncodeCnt3);
        this.lengthMap.put("usreasoncode4", Integer.valueOf(2));
        this.fieldMap.put("usreasoncode4", this.usreasoncode4);
        this.lengthMap.put("ireasoncodeCnt4", Integer.valueOf(4));
        this.fieldMap.put("ireasoncodeCnt4", this.ireasoncodeCnt4);
        this.lengthMap.put("usreasoncode5", Integer.valueOf(2));
        this.fieldMap.put("usreasoncode5", this.usreasoncode5);
        this.lengthMap.put("ireasoncodeCnt5", Integer.valueOf(4));
        this.fieldMap.put("ireasoncodeCnt5", this.ireasoncodeCnt5);
        this.lengthMap.put("usreasoncode6", Integer.valueOf(2));
        this.fieldMap.put("usreasoncode6", this.usreasoncode6);
        this.lengthMap.put("ireasoncodeCnt6", Integer.valueOf(4));
        this.fieldMap.put("ireasoncodeCnt6", this.ireasoncodeCnt6);
        this.lengthMap.put("iAntSwitchCnt", Integer.valueOf(4));
        this.fieldMap.put("iAntSwitchCnt", this.iAntSwitchCnt);
        this.lengthMap.put("iMainAntTime", Integer.valueOf(4));
        this.fieldMap.put("iMainAntTime", this.iMainAntTime);
        this.lengthMap.put("iSecAntTime", Integer.valueOf(4));
        this.fieldMap.put("iSecAntTime", this.iSecAntTime);
        this.lengthMap.put("iAvgRSSI", Integer.valueOf(4));
        this.fieldMap.put("iAvgRSSI", this.iAvgRSSI);
        this.enEventId.setValue("WIFI_DAILY_UPLOAD");
        this.usLen.setValue(getTotalLen());
    }
}
