package com.huawei.device.connectivitychrlog;

public class CSegEVENT_WIFI_WIFIPRO_EXCEPTION_EVENT extends ChrLogBaseEventModel {
    public LogByteArray aucAPSsid = new LogByteArray(32);
    public LogByteArray aucRO_APSsid = new LogByteArray(32);
    public ENCAC_FailType enAC_FailType = new ENCAC_FailType();
    public ENCAutoCloseRootCause enAutoCloseRootCause = new ENCAutoCloseRootCause();
    public ENCAutoOpenRootCause enAutoOpenRootCause = new ENCAutoOpenRootCause();
    public ENCBG_AC_DiffType enBG_AC_DiffType = new ENCBG_AC_DiffType();
    public ENCEventId enEventId = new ENCEventId();
    public ENCRATType enRATType = new ENCRATType();
    public ENCWifiProSubEvent enWifiProSubEvent = new ENCWifiProSubEvent();
    public LogInt iHomeAPJudgeTime = new LogInt();
    public LogString strAPBssid = new LogString(17);
    public LogString strREDIRECT_URL = new LogString(128);
    public LogDate tmTimeStamp = new LogDate(6);
    public LogByte ucAPSecurity = new LogByte();
    public LogByte ucCardIndex = new LogByte();
    public LogByte ucIPQLevel = new LogByte();
    public LogByte ucMobileSignalLevel = new LogByte();
    public LogShort usAutoOpenWhiteNum = new LogShort();
    public LogShort usCreditScoreRO_Rate = new LogShort();
    public LogShort usHighDataRateRO_Rate = new LogShort();
    public LogShort usHistoryQuilityRO_Rate = new LogShort();
    public LogShort usLen = new LogShort();
    public LogShort usOTA_PacketDropRate = new LogShort();
    public LogShort usRO_Duration = new LogShort();
    public LogShort usRSSI_VALUE = new LogShort();
    public LogShort usRttAvg = new LogShort();
    public LogShort usTcpInSegs = new LogShort();
    public LogShort usTcpOutSegs = new LogShort();
    public LogShort usTcpRetransSegs = new LogShort();
    public LogShort usWIFI_NetSpeed = new LogShort();

    public CSegEVENT_WIFI_WIFIPRO_EXCEPTION_EVENT() {
        this.lengthMap.put("enEventId", Integer.valueOf(1));
        this.fieldMap.put("enEventId", this.enEventId);
        this.lengthMap.put("usLen", Integer.valueOf(2));
        this.fieldMap.put("usLen", this.usLen);
        this.lengthMap.put("tmTimeStamp", Integer.valueOf(6));
        this.fieldMap.put("tmTimeStamp", this.tmTimeStamp);
        this.lengthMap.put("ucCardIndex", Integer.valueOf(1));
        this.fieldMap.put("ucCardIndex", this.ucCardIndex);
        this.lengthMap.put("enWifiProSubEvent", Integer.valueOf(1));
        this.fieldMap.put("enWifiProSubEvent", this.enWifiProSubEvent);
        this.lengthMap.put("usRSSI_VALUE", Integer.valueOf(2));
        this.fieldMap.put("usRSSI_VALUE", this.usRSSI_VALUE);
        this.lengthMap.put("usOTA_PacketDropRate", Integer.valueOf(2));
        this.fieldMap.put("usOTA_PacketDropRate", this.usOTA_PacketDropRate);
        this.lengthMap.put("usRttAvg", Integer.valueOf(2));
        this.fieldMap.put("usRttAvg", this.usRttAvg);
        this.lengthMap.put("usTcpInSegs", Integer.valueOf(2));
        this.fieldMap.put("usTcpInSegs", this.usTcpInSegs);
        this.lengthMap.put("usTcpOutSegs", Integer.valueOf(2));
        this.fieldMap.put("usTcpOutSegs", this.usTcpOutSegs);
        this.lengthMap.put("usTcpRetransSegs", Integer.valueOf(2));
        this.fieldMap.put("usTcpRetransSegs", this.usTcpRetransSegs);
        this.lengthMap.put("usWIFI_NetSpeed", Integer.valueOf(2));
        this.fieldMap.put("usWIFI_NetSpeed", this.usWIFI_NetSpeed);
        this.lengthMap.put("ucIPQLevel", Integer.valueOf(1));
        this.fieldMap.put("ucIPQLevel", this.ucIPQLevel);
        this.lengthMap.put("aucRO_APSsid", Integer.valueOf(32));
        this.fieldMap.put("aucRO_APSsid", this.aucRO_APSsid);
        this.lengthMap.put("ucMobileSignalLevel", Integer.valueOf(1));
        this.fieldMap.put("ucMobileSignalLevel", this.ucMobileSignalLevel);
        this.lengthMap.put("enRATType", Integer.valueOf(1));
        this.fieldMap.put("enRATType", this.enRATType);
        this.lengthMap.put("usHistoryQuilityRO_Rate", Integer.valueOf(2));
        this.fieldMap.put("usHistoryQuilityRO_Rate", this.usHistoryQuilityRO_Rate);
        this.lengthMap.put("usHighDataRateRO_Rate", Integer.valueOf(2));
        this.fieldMap.put("usHighDataRateRO_Rate", this.usHighDataRateRO_Rate);
        this.lengthMap.put("usCreditScoreRO_Rate", Integer.valueOf(2));
        this.fieldMap.put("usCreditScoreRO_Rate", this.usCreditScoreRO_Rate);
        this.lengthMap.put("aucAPSsid", Integer.valueOf(32));
        this.fieldMap.put("aucAPSsid", this.aucAPSsid);
        this.lengthMap.put("strAPBssid", Integer.valueOf(17));
        this.fieldMap.put("strAPBssid", this.strAPBssid);
        this.lengthMap.put("usRO_Duration", Integer.valueOf(2));
        this.fieldMap.put("usRO_Duration", this.usRO_Duration);
        this.lengthMap.put("usAutoOpenWhiteNum", Integer.valueOf(2));
        this.fieldMap.put("usAutoOpenWhiteNum", this.usAutoOpenWhiteNum);
        this.lengthMap.put("enAutoOpenRootCause", Integer.valueOf(1));
        this.fieldMap.put("enAutoOpenRootCause", this.enAutoOpenRootCause);
        this.lengthMap.put("enAutoCloseRootCause", Integer.valueOf(1));
        this.fieldMap.put("enAutoCloseRootCause", this.enAutoCloseRootCause);
        this.lengthMap.put("strREDIRECT_URL", Integer.valueOf(128));
        this.fieldMap.put("strREDIRECT_URL", this.strREDIRECT_URL);
        this.lengthMap.put("enAC_FailType", Integer.valueOf(1));
        this.fieldMap.put("enAC_FailType", this.enAC_FailType);
        this.lengthMap.put("ucAPSecurity", Integer.valueOf(1));
        this.fieldMap.put("ucAPSecurity", this.ucAPSecurity);
        this.lengthMap.put("iHomeAPJudgeTime", Integer.valueOf(4));
        this.fieldMap.put("iHomeAPJudgeTime", this.iHomeAPJudgeTime);
        this.lengthMap.put("enBG_AC_DiffType", Integer.valueOf(1));
        this.fieldMap.put("enBG_AC_DiffType", this.enBG_AC_DiffType);
        this.enEventId.setValue("WIFI_WIFIPRO_EXCEPTION_EVENT");
        this.usLen.setValue(getTotalLen());
    }
}
